services:
  web:
    build: web/
    env_file:
      - web/.env
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: api/
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - "postgres:postgres"

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./api/.scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 30s
